backend:
    name: git-gateway
    branch: main

media_folder: static/img
public_folder: /img

collections:
    - name: "settings"
      label: "Settings"
      files:
          - label: "Contact Information"
            name: contact_info
            file: site/settings/contact_info.json
            fields:
                - { label: "Phone", name: "phone", widget: "string" }
                - { label: "Email", name: "email", widget: "string" }
    - label: "Pages"
      name: "pages"
      files:
          - label: "About Page"
            name: "about"
            file: "site/content/about.json"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - {
                      label: "Mission Statement",
                      name: "mission",
                      widget: "text",
                  }
                - {
                      label: "Meaning of Daniel",
                      name: "meaning",
                      widget: "text",
                  }
                - {
                      label: "Primary Image",
                      name: "primary-image",
                      widget: "image",
                  }
                - {
                      label: "Background Primary",
                      name: "background-primary",
                      widget: "text",
                  }
                - {
                      label: "Background Secondary",
                      name: "background-secondary",
                      widget: "text",
                  }
                - {
                      label: "Remarks Primary",
                      name: "remarks-primary",
                      widget: "text",
                  }
                - {
                      label: "Remarks Secondary",
                      name: "remarks-secondary",
                      widget: "text",
                  }
                - {
                      label: "Secondary Image",
                      name: "secondary-image",
                      widget: "image",
                  }
